### PR TITLE
Loyalty Bundle - info readmes.

### PR DESCRIPTION
**Pull request by beardaway**
This change is [Reviewable](https://reviewable.io/reviews/estimote/ios-sdk/271)

### CODE REVIEW

**Comment by bprzemyslaw** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[Examples/README.md, line 42 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/271#-Kwt_qxrK02HrJLCAY6W:-Kwt_qxrK02HrJLCAY6X:b-kqyrck) ([raw file](https://github.com/estimote/ios-sdk/blob/d69bf4bfc73db9d46831f30ab8b39d17f8cce7ac/Examples/README.md#L42)):*
> ```Markdown
> - **Loyalty** (Swift only, requires Estimote Beacons with the 4th-gen firmware, 4.x+)
> 
> > Uses: Proximity beacons, beacon monitoring
> ```

Few suggestions:
"beacon monitoring" -> "Estimote Monitoring"
"Proximity beacons" -> "Estimote Proximity Beacons"

---

*[Examples/README.md, line 44 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/271#-Kwt_aPubcUty0TwzVNN:-Kwt_aPubcUty0TwzVNO:b-sc1fdp) ([raw file](https://github.com/estimote/ios-sdk/blob/d69bf4bfc73db9d46831f30ab8b39d17f8cce7ac/Examples/README.md#L44)):*
> ```Markdown
> > Uses: Proximity beacons, beacon monitoring
> 
> Cashier-customer app that allows cashiers to see customers at checkout in their iPad app and grant them their bonus points for their shopping. Completely new experience of earning points without carrying loyalty cards or scanning barcodes.
> ```

"grant them *their* bonus points" -> "grant them bonus points"?

---

*[Examples/swift/Loyalty/README.md, line 1 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/271#-KwtaObLsfImA-dKQOoH:-KwtaObLsfImA-dKQOoI:b-j01gue) ([raw file](https://github.com/estimote/ios-sdk/blob/d69bf4bfc73db9d46831f30ab8b39d17f8cce7ac/Examples/swift/Loyalty/README.md#L1)):*
> ```Markdown
> ### Loyalty app
> ```

These two `README.md`s (Loyalty and LoyaltyStore ones) look almost identical and we would have to update both of them each time we have a change to our dependency mechanism (we could use pods in other projects as well), so why not making it a chapter in the Examples/README.md? 
(then these two README.md's wouldn't be needed anymore)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/271)*

**Comment by beardaway** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[Examples/README.md, line 42 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/271#-Kwt_qxrK02HrJLCAY6W:-KwtcG_6ik-tgtvgya5T:b-896fix) ([raw file](https://github.com/estimote/ios-sdk/blob/d69bf4bfc73db9d46831f30ab8b39d17f8cce7ac/Examples/README.md#L42)):*
<details><summary><i>Previously, bprzemyslaw (Przemyslaw Blasiak) wrote…</i></summary><blockquote>

Few suggestions:
"beacon monitoring" -> "Estimote Monitoring"
"Proximity beacons" -> "Estimote Proximity Beacons"
</blockquote></details>

Done.

---

*[Examples/README.md, line 44 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/271#-Kwt_aPubcUty0TwzVNN:-Kwtc7g3s7vHCBjNYN4-:bw4s2y8) ([raw file](https://github.com/estimote/ios-sdk/blob/d69bf4bfc73db9d46831f30ab8b39d17f8cce7ac/Examples/README.md#L44)):*
<details><summary><i>Previously, bprzemyslaw (Przemyslaw Blasiak) wrote…</i></summary><blockquote>

"grant them *their* bonus points" -> "grant them bonus points"?
</blockquote></details>

Yep. That's how it's written in the cloud that's why I thought it was correct. Changed

---

*[Examples/swift/Loyalty/README.md, line 1 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/271#-KwtaObLsfImA-dKQOoH:-Kwtddn-FXUOb2lhTWCx:b-896fix) ([raw file](https://github.com/estimote/ios-sdk/blob/d69bf4bfc73db9d46831f30ab8b39d17f8cce7ac/Examples/swift/Loyalty/README.md#L1)):*
<details><summary><i>Previously, bprzemyslaw (Przemyslaw Blasiak) wrote…</i></summary><blockquote>

These two `README.md`s (Loyalty and LoyaltyStore ones) look almost identical and we would have to update both of them each time we have a change to our dependency mechanism (we could use pods in other projects as well), so why not making it a chapter in the Examples/README.md? 
(then these two README.md's wouldn't be needed anymore)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/271)*

**Comment by bprzemyslaw** [comment]
Reviewed 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Examples/swift/Loyalty/README.md, line 1 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/271#-KwtaObLsfImA-dKQOoH:-KwtgyWjtKOSlwZgG3Wi:b-myaw5l) ([raw file](https://github.com/estimote/ios-sdk/blob/d69bf4bfc73db9d46831f30ab8b39d17f8cce7ac/Examples/swift/Loyalty/README.md#L1)):*
<details><summary><i>Previously, beardaway (Konrad Sopala) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you remove this one as well? It looks like you didn't or maybe Reviewable is messing things up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/271)*

**Comment by beardaway** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Examples/swift/Loyalty/README.md, line 1 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/271#-KwtaObLsfImA-dKQOoH:-KwthQzLuIdRg6HjfEiW:b-896fix) ([raw file](https://github.com/estimote/ios-sdk/blob/d69bf4bfc73db9d46831f30ab8b39d17f8cce7ac/Examples/swift/Loyalty/README.md#L1)):*
<details><summary><i>Previously, bprzemyslaw (Przemyslaw Blasiak) wrote…</i></summary><blockquote>

Did you remove this one as well? It looks like you didn't or maybe Reviewable is messing things up?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/271)*

**Comment by bprzemyslaw** [comment]
Reviewed 1 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/271)*

**Pull request merged**
