### PR TITLE
Daver/emoji explorer/error handling

### PR DESCRIPTION
**Pull request by daverPL**
This change is [Reviewable](https://reviewable.io/reviews/estimote/ios-sdk/243)

### CODE REVIEW

**Comment by bprzemyslaw** [comment]
*[Examples/swift/EmojiAdvertiser/EmojiAdvertiser/EmojiScanner.swift, line 140 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/243#-KYxLFbo3T64KbuN9wvj:-KYxLFbo3T64KbuN9wvk:bkhy0nm) ([raw file](https://github.com/estimote/ios-sdk/blob/c2f5b0a4d979e462c4ba571c59c1b7e9e0f75563/Examples/swift/EmojiAdvertiser/EmojiAdvertiser/EmojiScanner.swift#L140)):*
> ```Swift
> extension EmojiScanner: Error {
>     
>     enum EmojiScannerError: Int {
> ```

You should inherit from Error HERE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/243)*

**Comment by bprzemyslaw** [comment]
*[Examples/swift/EmojiAdvertiser/EmojiAdvertiser/NearestEmojiVC.swift, line 1 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/243#-KYxNUEmXCIqp9NXAMNI:-KYxNUEnVJS84piFZNCO:bo6wdti) ([raw file](https://github.com/estimote/ios-sdk/blob/c2f5b0a4d979e462c4ba571c59c1b7e9e0f75563/Examples/swift/EmojiAdvertiser/EmojiAdvertiser/NearestEmojiVC.swift#L1)):*
> ```Swift
> //  Copyright © 2016 Estimote. All rights reserved.
> ```

Could you update headers in all files?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/243)*

**Comment by bprzemyslaw** [comment]
*[Examples/swift/EmojiAdvertiser/EmojiAdvertiser/EmojiScanner.swift, line 140 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/243#-KYxLFbo3T64KbuN9wvj:-KYxNfIXKk3hljbbpITV:btb8jbb) ([raw file](https://github.com/estimote/ios-sdk/blob/c2f5b0a4d979e462c4ba571c59c1b7e9e0f75563/Examples/swift/EmojiAdvertiser/EmojiAdvertiser/EmojiScanner.swift#L140)):*
<details><summary><i>Previously, bprzemyslaw (Przemyslaw Blasiak) wrote…</i></summary><blockquote>

You should inherit from Error HERE
</blockquote></details>

I mean implement the protocol :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/243)*

**Comment by bprzemyslaw** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/243)*

**Comment by bprzemyslaw** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/243)*

**Comment by bprzemyslaw** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/243#-:-KYxiKdFhpV6hG0kxeTn:bnfp4nl)*

**Comment by daverPL** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Examples/swift/EmojiAdvertiser/EmojiAdvertiser/EmojiScanner.swift, line 140 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/243#-KYxLFbo3T64KbuN9wvj:-KYxidaOH35v_O5vEKrw:b-896fix) ([raw file](https://github.com/estimote/ios-sdk/blob/c2f5b0a4d979e462c4ba571c59c1b7e9e0f75563/Examples/swift/EmojiAdvertiser/EmojiAdvertiser/EmojiScanner.swift#L140)):*
<details><summary><i>Previously, bprzemyslaw (Przemyslaw Blasiak) wrote…</i></summary><blockquote>

I mean implement the protocol :D
</blockquote></details>

Done.

---

*[Examples/swift/EmojiAdvertiser/EmojiAdvertiser/NearestEmojiVC.swift, line 1 at r1](https://reviewable.io:443/reviews/estimote/ios-sdk/243#-KYxNUEmXCIqp9NXAMNI:-KYxicmu8p_DfelytoOI:b-896fix) ([raw file](https://github.com/estimote/ios-sdk/blob/c2f5b0a4d979e462c4ba571c59c1b7e9e0f75563/Examples/swift/EmojiAdvertiser/EmojiAdvertiser/NearestEmojiVC.swift#L1)):*
<details><summary><i>Previously, bprzemyslaw (Przemyslaw Blasiak) wrote…</i></summary><blockquote>

Could you update headers in all files?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/estimote/ios-sdk/243)*

**Pull request merged**
